### ISSUE TITLE
Ollama is unreachable 

### ISSUE THREAD

**Issue by qrkourier** [AugustDev/enchanted#2]
Hi 👋

I'm trying out the new version 1.0.1. I can reach ollama in a web browser, but apparently not in Enchanted. 

![signal-2023-12-20-00-59-33-425-1](https://github.com/AugustDev/enchanted/assets/1434400/6030c1b8-4adb-4b53-848c-a2a79b79374e)
<img width="375" alt="signal-2023-12-20-00-57-33-191" src="https://github.com/AugustDev/enchanted/assets/1434400/ac657657-cb98-4763-afda-29e50ee1c3a8">
![signal-2023-12-20-00-59-33-425](https://github.com/AugustDev/enchanted/assets/1434400/4d28d308-bfcb-4073-892f-84e0d5d9ff61)

**Comment by qrkourier** [comment]
Looking at Ollamakit, I’m pretty sure this is a valid base URL because all the HTTP routes are defined as URL paths following the HTTP origin that is ollamaUri. 

![IMG_0009](https://github.com/AugustDev/enchanted/assets/1434400/bc8440ac-4b4d-463e-91c9-613def17c545)

**Comment by qrkourier** [comment]
Confirmed that OK.reachable() is requesting baseUrl/

That is loading okay in the web browser. 

![IMG_0011](https://github.com/AugustDev/enchanted/assets/1434400/51afcf94-1327-43ba-b5b2-a8ba1355663e)

**Comment by AugustDev** [comment]
Hi @qrkourier thanks for making the issue! Your screenshots were very helpful. The problem was that iOS rejected non https domains by default. I have made a fix and releasing new version of the app ASAP. Hopefully will be approved by Apple later today or tomorrow morning.

**Comment by qrkourier** [comment]
That makes sense! You probably didn't encounter the issue because you proxied the API through an ngrok HTTPS endpoint. I should have tried that.

**Comment by AugustDev** [comment]
Hi @qrkourier new version was just approved on App Store. I fixed this issue and added some new features. Please let me know if you find other issues!

**Comment by qrkourier** [comment]
I used a web browser to verify the base API URL showed "Ollama is running", then I installed an Enchanted app update from the App Store, force-closed Enchanted by swiping up in the switcher, then I re-opened Enchanted and double-checked the base API URL is the same as the one I tested. After a few seconds I still see the error message about Ollama being unreachable.

**Comment by qrkourier** [comment]
Next, I'll install a pending iOS update on this iPhone SE and check if it works for me with an HTTPS base API URL. Are you running Ollama 0.1.16 too?

**Comment by AugustDev** [comment]
Perhaps you can explain how you obtain HTTP url, so I can try to reproduce it exactly the same way? I am using Ollama 0.1.17.

I also had a think about your comment with different response. I use Ollama [chat API](https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-chat-completion) on the app. This is because it handles conversations much better.

**Comment by qrkourier** [comment]
@AugustDev I found it is working after I installed the iOS update v17.2.1 and rebooted. I suspect that the updated app was not actually running even though I'd installed the update, or that somehow rebooting the iPhone solved a temporary problem.

**Comment by AugustDev** [comment]
Ah great news!
